### ISSUE TITLE
Puzzles

### ISSUE THREAD

**Issue by kettek** [kettek/ebijam23#4]
This issue provides some puzzling about puzzles.

**Comment by kettek** [comment]
In relation to a previous discussion about destructible walls based upon DPS, I noticed that with Deflect and Reverse, one can reverse projectiles to pile them up, then just use deflect to yeet them in a direction. This is in addition to the previous notion I held to just build with reverse, then dodge to let them hit a wall behind you.

At any rate, that seems to be a decent idea for bypassing walls/barriers.

In regards to this DPS wall/area, it should probably have either an HP bar over/under it that shows it regenerating (like the player's old energy bar), or some other visual indicator that somehow indicates it weakening under the amount of DPS. The bar would be the most obvious and straightforward, but it might not be the best we could do -- requires more thought.

**Comment by liqMix** [comment]
As an alternate to a bar, we could do the ole' increase red as it nears destruction. That would allow us to fade it back to its original colors to show its strength regaining

**Comment by kettek** [comment]
Genius
